---
- name: Get existing config.toml
  ansible.builtin.slurp:
    src: "{{ gitlab_runner_config_file }}"
  register: runner_config_file
  tags: runner_runners_config

- name: Get pre-existing runner configs
  ansible.builtin.set_fact:
    runner_configs: "{{ (runner_config_file['content'] | b64decode).split('[[runners]]\n') }}"
  tags: runner_runners_config

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: gitlab-runner-config
  register: temp_runner_config_dir
  check_mode: no
  changed_when: false
  tags: runner_runners_config

- name: Write config section for each runner
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/config/config-runner.yml"
  vars:
    conf_name_prefix: "conf[{{ (runner_config_index | int) + 1 }}/{{ runner_configs | length }}]:"
  loop: "{{ runner_configs }}"
  loop_control:
    index_var: runner_config_index
    loop_var: runner_config
  tags: runner_runners_config

- name: Assemble new Runner config file
  ansible.builtin.assemble:
    src: "{{ temp_runner_config_dir.path }}"
    dest: "{{ gitlab_runner_config_file }}"
    delimiter: '[[runners]]\n'
    backup: true
    validate: "{{ gitlab_runner_service }} verify -c %s"
    mode: '0600'
  diff: "{{ gitlab_runner_show_config_diff | bool }}"
  tags: runner_runners_config
