---
# handlers file for role-gitlab_runner
- name: (Handler) Start/reload Runner
  ansible.builtin.service:
    name: "{{ gitlab_runner_service }}"
    state: reloaded
    enabled: true
  when:
    - gitlab_runner_start | bool
    - gitlab_runner_state != 'absent'
  listen: (Handler) Run Runner

- name: (Handler) Delete Runners
  ansible.builtin.command:
    cmd: "{{ gitlab_runner_service }} verify --delete"
  register: verified_runners
  changed_when: '"Updated " in verified_runners.stderr'
  check_mode: no
  listen: (Handler) Run Runner

- name: (Handler) Check Runner
  ansible.builtin.command:
    cmd: "{{ gitlab_runner_service }} verify"
  register: config_check
  ignore_errors: true
  check_mode: false
  changed_when: false
  when: gitlab_runner_state != 'absent'
  listen: (Handler) Run Runner

- name: (Handler) Print Runner error if syntax check fails
  ansible.builtin.debug:
    var: config_check.stderr_lines
  failed_when: config_check['rc'] != 0
  when:
    - config_check['stderr_lines'] is defined
    - config_check['stderr_lines'] != []
    - config_check['rc'] != 0
    - gitlab_runner_state != 'absent'
  listen: (Handler) Run Runner
