---
- name: List configured runners as json
  ansible.builtin.command: '{{ gitlab_runner_service }} --log-format json list'
  register: registered_runners_json_result
  changed_when: False
  check_mode: no
  tags: runner_setup_config

- name: Initialze runner list
  ansible.builtin.set_fact:
    registered_gitlab_runner_names: []
  tags: runner_setup_config

- name: Create list of configured runners
  ansible.builtin.set_fact:
    registered_gitlab_runner_names: "{{ registered_gitlab_runner_names + [json_item['msg']] }}"
  vars:
    json_item: "{{ item | from_json }}"
  loop: "{{ registered_runners_json_result.stderr_lines }}"
  when: "'Executor' in json_item"
  tags: runner_setup_config

- name: Print registered runners
  ansible.builtin.debug:
    var: registered_gitlab_runner_names
  tags: runner_setup_config
