---
- name: Construct the runner command without secrets
  ansible.builtin.set_fact:
    register_runner_cmd: >-
      {{ gitlab_runner_service }} register
      --non-interactive
      --name '{{ gitlab_runner.name }}'
      --url '{{ gitlab_runner.url | default(gitlab_runner_coordinator_url) }}'
      --executor "{{ gitlab_runner.executor }}"
      {% if gitlab_runner.clone_url | default(false) %}
      --clone-url "{{ gitlab_runner.clone_url }}"
      {% endif %}
      {% if gitlab_runner.tls_ca_file | default(false) %}
      --tls-ca-file "{{ gitlab_runner.tls_ca_file }}"
      {% endif %}
      {% if gitlab_runner.shell is defined %}
      --shell '{{ gitlab_runner.shell }}'
      {% endif %}
      --limit '{{ gitlab_runner.limit | default(0) }}'
      {% for env_var in gitlab_runner.env_vars | default([]) %}
      --env '{{ env_var }}'
      {% endfor %}
      {% if (gitlab_runner.executor is defined) and (gitlab_runner.executor == 'docker') %}
      --docker-image '{{ gitlab_runner.docker_image | default("alpine") }}'
      {% for volume in gitlab_runner.docker_volumes|default([]) %}
      --docker-volumes "{{ volume }}"
      {% endfor %}
      {% endif %}
      {% if gitlab_runner.cache_type is defined %}
      --cache-type '{{ gitlab_runner.cache_type }}'
      {% endif %}
      {% if gitlab_runner.cache_shared | default(false) %}
      --cache-shared
      {% endif %}
      {% if gitlab_runner.cache_path is defined %}
      --cache-path '{{ gitlab_runner.cache_path }}'
      {% endif %}
      {% if gitlab_runner.cache_s3_server_address is defined %}
      --cache-s3-server-address '{{ gitlab_runner.cache_s3_server_address }}'
      {% endif %}
      {% if gitlab_runner.cache_s3_access_key is defined %}
      --cache-s3-access-key '{{ gitlab_runner.cache_s3_access_key }}'
      {% endif %}
      {% if gitlab_runner.cache_s3_bucket_name is defined %}
      --cache-s3-bucket-name '{{ gitlab_runner.cache_s3_bucket_name }}'
      {% endif %}
      {% if gitlab_runner.cache_s3_bucket_location is defined %}
      --cache-s3-bucket-location '{{ gitlab_runner.cache_s3_bucket_location }}'
      {% endif %}
      {% if gitlab_runner.cache_dir | default(false) %}
      --cache-dir '{{ gitlab_runner.cache_dir }}'
      {% endif %}
      {% if gitlab_runner.cache_s3_insecure | default(false) %}
      --cache-s3-insecure
      {% endif %}
  when:
    - gitlab_runner is defined
    - gitlab_runner | length > 0
  tags: runner_setup_config
