---
- name: Check whether you are using a supported GitLab Runner distribution
  ansible.builtin.assert:
    that:
      - "{{ ansible_facts['distribution'] | lower in gitlab_runner_distributions.keys() | list }}"
      - "{{ (ansible_facts['distribution_version'] | regex_search('\\d{1,2}\\.\\d{2}') | float in gitlab_runner_distributions[ansible_facts['distribution'] | lower]['versions'] | map('float'))
        if ansible_facts['distribution'] | lower in ['ubuntu'] else ansible_facts['distribution_major_version'] in gitlab_runner_distributions[ansible_facts['distribution'] | lower]['versions'] | string }}"
      - "{{ ansible_facts['architecture'] in gitlab_runner_distributions[ansible_facts['distribution'] | lower]['architectures'] }}"
    success_msg: Your distribution, {{ gitlab_runner_distributions[ansible_facts['distribution'] | lower]['name'] }} {{ ansible_facts['distribution_version'] }} ({{ ansible_facts['architecture'] }}), is supported by GitLab Runner.
    fail_msg: Your distribution, {{ gitlab_runner_distributions[ansible_facts['distribution'] | lower]['name'] }} {{ ansible_facts['distribution_version'] }} ({{ ansible_facts['architecture'] }}), is not supported by GitLab Runner.
  ignore_errors: true
  register: gitlab_runner_support_validate

- name: Check that 'gitlab_runner_setup' is an allowed value
  ansible.builtin.assert:
    that: gitlab_runner_setup in gitlab_runner_setup_vars
    fail_msg: The value you used for 'gitlab_runner_setup', {{ gitlab_runner_setup }}, is not allowed. The allowed values are [{{ gitlab_runner_setup_vars | join(', ') }}].
  ignore_errors: true
  register: gitlab_runner_setup_validate
